version: "2"
services:
  billing:
    image: storjlabs/billing
    build:
      context: ../
      dockerfile: ./dockerfiles/billing-development.dockerfile
    volumes:
      - ../lib:/billing/lib
      - ../bin:/billing/bin
      - ../index.js:/billing/index.js
      - ../package.json:/billing/package.json
    environment:
      STAGE: development
      MONGO_URL: 'mongodb://mongo:27017/__storj-bridge-development'
    links:
      - mongo
    ports:
      - '3000:3000'
  mongo:
    image: mongo
    ports:
     - '27017:27017'
