version: "2"
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  billing:
    build:
      context: ..
      dockerfile: ./dockerfiles/billing-develop.dockerfile
    ports:
      - '3000:3000'
    working_dir: '/billing'
    command: /usr/bin/env npm run start-dev
    environment:
      NODE_ENV: 'develop'
    volumes:
      - ../bin:/billing/bin
      - ../lib:/billing/lib
    links:
      - mongo
