version: "2"
services:
  ruby:
    build:
      context: ..
      dockerfile: ./dockerfiles/selenium-test.dockerfile
    working_dir: '/billing'
    command: ['/usr/bin/env', 'cucumber']
    volumes:
      - ../features:/billing/features
      - ../script:/billing/script
