version: "2"
services:
  mongo:
    image: mongo
    ports:
      - '27018:27017'
  billing:
    build:
      context: ..
      dockerfile: ./dockerfiles/billing-develop.dockerfile
    ports:
      - '6383:6382'
    working_dir: '/billing'
    command: /usr/bin/env node /billing/bin/storj-billing.js
    environment:
      NODE_ENV: 'test'
    volumes:
      - ../bin:/billing/bin
      - ../lib:/billing/lib
    links:
      - mongo
  ruby:
    build:
      context: ..
      dockerfile: ./dockerfiles/selenium-test.dockerfile
    working_dir: '/billing'
    command: ['/usr/bin/env', 'cucumber']
    volumes:
      - ../features:/billing/features
      - ../script:/billing/script
    links:
      - billing
      - mongo
